### ISSUE TITLE
'Configuration' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by irom77** [StackStorm-Exchange/stackstorm-msexchange#5]
When running $ st2 run msexchange.search_items I am getting error below:
```
..
id: 5a8dce1c5014005a99230f52
status: failed
parameters: None
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 275, in <module>\n    obj.run()\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 162, in run\n    action = self._get_action_instance()\n  File \"/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py\", line 240, in _get_action_instance\n    action_service=action_service)\n  File \"/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/runners/utils.py\", line 98, in get_action_class_instance\n    action_instance = action_cls(**kwargs)\n  File \"/opt/stackstorm/packs/msexchange/actions/base/action.py\", line 51, in __init__\n    primary_smtp_address=config['primary_smtp_address'],\nTypeError: 'Configuration' object has no attribute '__getitem__'\n"
  stdout: ''

```
Complaining about primary_smtp_address which is I think fine
```
$ cat /opt/stackstorm/configs/msexchange.yaml
---
primary_smtp_address: "netpro-reply@common.com"
username: "netpro-reply@common.com"
password: "password"
timezone: "America/New_York"
server: mailserver.common.com
```
